defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.train_ppo_diffusion_img_agent.TrainPPOImgDiffusionAgent

name: ${env_name}_ft_diffusion_mlp_img_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/maniskill-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: /ML-vePFS/tangyinzhou/yinuo/dp_train_zhiting/ckpts/20250914_094502/policy_step_140000_seed_0.ckpt
normalization_path: /ML-vePFS/tangyinzhou/yinuo/dp_train_zhiting/ckpts/20250914_094502/norm_stats_1_epsnum_500.pkl


num_img: 2
seed: 42
device: cuda:0
env_name: TabletopPickPlaceEnv-v1
obs_dim: 10
img_feature_dim: 128
action_dim: 10
denoising_steps: 50
ft_denoising_steps: 10
cond_steps: 1
img_cond_steps: 1
horizon_steps: 20
act_steps: 20
use_ddim: True

object_name: nonstop
container_name: plate
robot_uids: panda_wristcam


env:
  n_envs: 8
  name: ${env_name}
  object_name: ${object_name}
  container_name: ${container_name}
  robot_uids: ${robot_uids}
  best_reward_threshold_for_success: 1
  max_episode_steps: 300
  save_video: False
  use_image_obs: True
  wrappers:
    maniskill_image:
      normalization_path: ${normalization_path}
      low_dim_keys: []
      image_keys: ['3rd_view_camera', 'hand_camera']
      shape_meta: ${shape_meta}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

shape_meta:
  obs:
    rgb:
      shape: [6, 224, 224]
    state:
      shape: [10]
  action: 
    shape: [7]

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: maniskill-${env_name}-finetune
  run: ${now:%H-%M-%S}_${name}

train:
  n_train_itr: 151
  n_critic_warmup_itr: 10
  n_steps: 120
  gamma: 0.999
  augment: False
  grad_accumulate: 100
  actor_lr: 3e-5
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 3e-5
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: ${train.n_train_itr}
    warmup_steps: 10
    min_lr: 1e-3
  save_model_freq: 100
  val_freq: 10
  render:
    freq: 1
    num: 0
  # PPO specific
  reward_scale_running: True
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 96
  logprob_batch_size: 96
  update_epochs: 6
  vf_coef: 0.5
  target_kl: 1

model:
  _target_: model.diffusion.diffusion_ppo.PPODiffusion
  # HP to tune
  denoised_clip_value: 1
  gamma_denoising: 0.99
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.001
  clip_ploss_coef_rate: 3
  randn_clip_value: 3
  min_sampling_denoising_std: 0.1
  min_logprob_denoising_std: 0.1
  #
  use_ddim: ${use_ddim}
  ddim_steps: ${ft_denoising_steps}
  learn_eta: False
  eta:
    base_eta: 0.6
    input_dim: ${obs_dim}
    mlp_dims: [256, 256]
    action_dim: ${action_dim}
    min_eta: 0.1
    max_eta: 1.0
    _target_: model.diffusion.eta.EtaFixed
  network_path: ${base_policy_path}
  actor:
    _target_: model.diffusion.mlp_diffusion_resnet.VisionDiffusionMLP
    backbone:
      _target_: model.common.resnet.ResNetEncoder
      input_channel: ${eval:'3 * ${img_cond_steps}'} # each image patch is history concatenated
      pretrained: False
      input_coord_conv: False
    augment: False
    num_img: ${num_img}
    time_dim: 32
    mlp_dims: [512, 512, 512]
    residual_style: True
    img_cond_steps: ${img_cond_steps}
    cond_dim: ${eval:'${img_feature_dim} + ${obs_dim} * ${cond_steps}'}  # 128 (visual features) + 10 (state features) = 138
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  critic:
    _target_: model.common.critic.ResNetCritic
    augment: False
    num_img: ${num_img}
    backbone:
      _target_: model.common.resnet.ResNetEncoder
      input_channel: ${eval:'3 * ${img_cond_steps}'} # each image patch is history concatenated
      pretrained: False
      input_coord_conv: False
    img_cond_steps: ${img_cond_steps}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
    cond_dim: ${eval:'${img_feature_dim} + ${obs_dim} * ${cond_steps}'}  # 128 (visual features) + 10 (state features) = 138
  ft_denoising_steps: ${ft_denoising_steps}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}
